# fly.toml app configuration file generated for xxx-windmill-minimal on 2023-08-02T16:46:27+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xxx-windmill-minimal"
primary_region = "sea"

[env]
  BASE_URL = "https://xxx-windmill-minimal.fly.dev/"
  KEEP_JOB_DIR = "false"
  NUM_WORKERS = "4"
  RUST_LOG = "info"

[[mounts]]
  source = "worker_cache"
  destination = "/tmp/windmill/cache"

[http_service]
  internal_port = 80
  force_https = true
