# fly.toml app configuration file generated for xxx-windmill-lsp on 2023-08-02T17:16:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "xxx-windmill-lsp"
primary_region = "sea"

[build]
  image = "ghcr.io/windmill-labs/windmill-lsp:latest"

[[mounts]]
  source = "lsp_cache"
  destination = "/root/.cache"

[http_service]
  internal_port = 3001
  #auto_stop_machines = true
  #auto_start_machines = true
